import com.alibaba.fastjson.JSONObject;
import org.hyperledger.fabric.client.Contract;
import org.hyperledger.fabric.client.EndorseException;

import javax.swing.*;
import java.awt.*;


/**
 *
 * @author carmenw
 */
public class QueryReport extends JFrame {

    /**
     * Creates new form NewJPanel
     */

    public static void main(String[] args){
        QueryReport f = new QueryReport();
        System.out.println("exit");
    }
    private JButton ButtonCancel;
    private JButton ButtonSummit;
    private JLabel TextMessage;
    private JLabel TextTitle;
    private JTextField PaperIDField;
    //FabricGateway fabricGateway = new FabricGateway();


    public QueryReport() {

        this.setSize(400, 200);
        //this.setMinimumSize(new Dimension(800, 500));
        this.setLocation(160, 160);
        this.setTitle("Query Report");
        this.setResizable(false);
        this.setVisible(false);


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">

        TextMessage = new JLabel();
        ButtonSummit = new JButton();
        ButtonCancel = new JButton();
        TextTitle = new JLabel();
        PaperIDField = new JTextField();

        TextMessage.setText("Please enter the PaperID:");

        ButtonSummit.setText("Summit");
        ButtonSummit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSummitActionPerformed(evt);
            }
        });

        ButtonCancel.setText("Cancel");
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });
/*        ButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                ButtonCancelMousePressed(evt);
            }
*//*            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCancelMouseClicked(evt);
            }*//*
        });*/

        TextTitle.setText("--- PAPER SYSTEM ---");
        Font f = new Font("Arial",Font.BOLD,16);
        TextTitle.setFont(f);

        PaperIDField.setText("");
        PaperIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaperIDFieldActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this.getContentPane());
        this.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ButtonSummit)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonCancel)
                                .addGap(44, 44, 44))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextTitle)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(TextMessage)
                                                .addGap(85, 85, 85))
                                        .addComponent(PaperIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(356, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(18, Short.MAX_VALUE)
                                .addComponent(TextTitle)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(TextMessage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PaperIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ButtonSummit)
                                        .addComponent(ButtonCancel))
                                .addContainerGap(26, Short.MAX_VALUE))
        );
    }

    private void ButtonSummitActionPerformed(java.awt.event.ActionEvent evt) {

        if(PaperIDField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Queried PaperID",
                    "Warning", JOptionPane.WARNING_MESSAGE,UIManager.getIcon("OptionPane.warningIcon"));
            return;
        }
        else{
            ResponseReport report = new ResponseReport();
            report.TextPaperID.setText("Paper ID: "+PaperIDField.getText().trim());
            try {
                JOptionPane.showMessageDialog(null, "Please wait, Loading now... \n" +
                                "Press OK to continue",
                        "Loading", JOptionPane.PLAIN_MESSAGE);

                Contract contract = Login.fabricGateway.getContract();
                //String str = "{\"selector\":{\"ai\":\"true\",\"ReviewState\":\"true\"}, \"use_index\":[]}";// 富查询字符串
                byte[] normalQueries = contract.submitTransaction("queryData", PaperIDField.getText().trim());
                //byte[] normalQueries = contract.submitTransaction("queryData", "paper000");

                String s = new String(normalQueries);
                System.out.println("s" + s);

                //String YourMessage = "";
                JSONObject jsonObject = JSONObject.parseObject(s);
                System.out.println("s1" + jsonObject);
                System.out.println("s2" + jsonObject.get("MarkedBy"));
                System.out.println("s3" + jsonObject.get("report"));
                System.out.println(jsonObject.size());
                report.TextMarkby.setText("Marked By: "+jsonObject.get("MarkedBy"));
                report.ReportField.setText( (String)jsonObject.get("report") );
                report.setVisible(true);
            }
            catch(EndorseException e){
                JOptionPane.showMessageDialog(null, "No Such A Paper,"+"\n"+"Please Enter A Valid PaperID",
                        "Warning", JOptionPane.ERROR_MESSAGE,UIManager.getIcon("OptionPane.warningIcon"));
                return;
            }
            catch (Exception e){
                System.out.println("Error Message");
                JOptionPane.showMessageDialog(null, "UnExpected Error\n" +
                                "Please Try Again.",
                        "Error Message", JOptionPane.ERROR_MESSAGE,UIManager.getIcon("OptionPane.errorIcon"));
                return;
            }
        }
        PaperIDField.setText("");
    }

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {
        PaperIDField.setText("");
        this.setVisible(false);
    }
/*    private void ButtonCancelMousePressed(java.awt.event.MouseEvent evt) {
        this.setVisible(false);
        System.out.println("click Cancel InVisible");
    }*/

    private void PaperIDFieldActionPerformed(java.awt.event.ActionEvent evt) {
    }

}
